### ISSUE TITLE
Forward slashes escaping

### ISSUE THREAD

**Issue by zmeyc** [axelhzf/create-react-app-docker-environment-variables#1]
In docker-entrypoint.sh `"`-s and `/`-s are escaped.
```
sed 's/\"/\\\"/g' | sed 's/\//\\\//g'
```
Are backslashes were supposed to be escaped instead? Because \ is control char in string and " can close the string. / is not special afaik if I'm not missing anything.

**Comment by zmeyc** [comment]
Escaping + few other fixes:
https://github.com/axelhzf/create-react-app-docker-environment-variables/pull/2

UPD:
I now see, / is for sed (but it needs a lot of other chars escaped as well). I'll update PR if I find how to escape sed's dest correctly.

**Comment by zmeyc** [comment]
Fixed sed escaping and updated the PR.

**Comment by axelhzf** [comment]
#2 merged
